### ISSUE TITLE
Patient tracking still needs to be added to site

### ISSUE THREAD

**Issue by TimStallard** [terminal-velocity/terminal-velocity.github.io#4]

**Comment by ir-g** [comment]
Use https://github.com/terminal-velocity?utf8=%E2%9C%93&query=patient-track this link to list all related repos

**Comment by TimStallard** [comment]
What should I call the project? Was it Patient Tracking, or just Patient Track?

**Comment by ir-g** [comment]
Patient Track, I guess

**Comment by TimStallard** [comment]
👍
